config/routes.rb
Rails.application.routes.draw do
  resources :experiments, only: [:index, :show, :update]

  resources :investigators, only: [:index, :show]
  resources :developers, only: [:index, :show]
  resources :expeditions, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :subcategories, only: [:index, :show]
  resources :space_agencies, only: [:index, :show]
  resources :organizations, only: [:index, :show]
  resources :keywords

  root "experiments#index"
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  belongs_to :space_agency
  belongs_to :organization
  has_and_belongs_to_many :developers
  has_and_belongs_to_many :expeditions
  has_and_belongs_to_many :investigators
  has_and_belongs_to_many :keywords

  validates :name, presence: true, uniqueness: true
  validates :external_id, presence: true, uniqueness: true

  default_scope { order(:name) }
  scope :unrevised, -> { where(revised: false) }
  scope :revised, -> { where(revised: true) }
  scope :complete, -> { includes(:category, :subcategory, :space_agency, :organization, :developers, :expeditions, :investigators, :keywords)}
  scope :by_initial, ->(initial) { where("lower(name) LIKE ?", initial.downcase + "%") }

  def self.initials
    Experiment.unscoped.all.select(:name).map {|e| e.name[0].upcase}.uniq.compact.sort
  end

  def revised!
    update_attribute(:revised, true)
  end

  def docking_dates
    dock_on = dock_date.present? ? dock_date.strftime("%d/%m/%Y") : "unavailable"
    undock_on = undock_date.present? ? undock_date.strftime("%d/%m/%Y") : "-"

    if dock_on == "unavailable" && undock_on == "-"
      return "No docking info available"
    else
      return "Docked from #{dock_on} to #{undock_on}"
    end
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :admin_required, except: [:index]

  def index
    if params[:by_initial].present?
      @experiments = Experiment.by_initial(params[:by_initial])
    else
      @experiments = Experiment.all
    end
  end

  def show
    @experiment = Experiment.complete.find(params[:id])
  end

  def update
    @experiment = Experiment.find(params[:id])
    if @experiment.update(experiment_params)
      @experiment.revised!
      redirect_to experiment_url(@experiment), notice: "Experiment was successfully updated!"
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def experiment_params
      params.require(:experiment).permit(:completed_successfully,
                                         :commercial,
                                         :crew_involvement,
                                         :required_sample_return,
                                         :hardware_required,
                                         :data_in_repositories,
                                         :sample_return_times,
                                         :crew_involvement_description,
                                         :data_in_respositories_details,
                                         :hardware_required_details,
                                         { keyword_ids: [] })
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
  def revised_icon(exper, size=16)
    if exper.revised
      "<img src='/checked.png' width='#{size}px'>".html_safe
    end
  end
end

app/views/experiments/_experiment.html.erb
<h2><%= revised_icon(experiment, 32) %> <%= experiment.name %></h2>

<aside>
  <%= render 'form', experiment: experiment %>
</aside>

<p class="experiment-title"><strong><i><%= experiment.title %></i></strong></p>

<p>
  <strong>Category:</strong> <%= link_to experiment.category.name, category_path(experiment.category)%>
  <% if experiment.subcategory.present? %>
    <strong>Subcategory:</strong> <%= link_to experiment.subcategory.name, subcategory_path(experiment.subcategory)%>
  <% end %>
</p>
<p><strong>Sponsoring Space Agency:</strong> <%= link_to experiment.space_agency.name, space_agency_path(experiment.space_agency) %></p>
<p><strong>Supporting Organization:</strong> <%= link_to experiment.organization.name, organization_path(experiment.organization) if experiment.organization %></p>
<p>
  <strong><%= pluralize experiment.expeditions.size, "Expedition" %>:</strong>
  <% experiment.expeditions.each do |exp| %>
    <%= link_to exp.name, exp %>
  <% end %>
</p>

<p><strong><%= experiment.docking_dates %></strong></p>

<p>
  <% experiment.keywords.each do |key| %>
    <span class="keyword keyword-<%= key.id %>"><%= key.name %></span>
  <% end %>
</p>

<div id="pao-summary"><%= experiment.pao_summary.to_s.html_safe %></div>

<% if experiment.research_summary.present? || experiment.research_description.present? %>
<p><strong>Research</strong></p>
<div id="research-summary"><%= experiment.research_summary.to_s.html_safe %></div>
<br>
<div id="research-description"><%= experiment.research_description.to_s.html_safe %></div>
<% end %>

<% if experiment.research_operations.present? %>
<p><strong>Operations</strong></p>
<div id="research-operations"><%= experiment.research_operations.html_safe %></div>
<% end %>

<% if experiment.applications_in_space.present? %>
<p><strong>Applications in space</strong></p>
<div id="research-operations"><%= experiment.applications_in_space.html_safe %></div>
<% end %>

<% if experiment.applications_on_earth.present? %>
<p><strong>Applications on Earth</strong></p>
<div id="research-operations"><%= experiment.applications_on_earth.html_safe %></div>
<% end %>

<% if experiment.results_summary.present? || experiment.results.present? %>
<p><strong>Results</strong></p>
<div id="results-summary"><%= experiment.results_summary.to_s.html_safe %></div>
<br>
<div id="results"><%= experiment.results.to_s.html_safe %></div>
<% end %>

<% if experiment.res_ops_reqs_protos.present? %>
<p><strong>Res. Ops. Reqs. Protos.</strong></p>
<div id="res-ops-reqs-protos"><%= experiment.res_ops_reqs_protos.html_safe %></div>
<% end %>

<% if experiment.decadals.present? %>
<p><strong>Decadals</strong></p>
<div id="decadals"><%= experiment.decadals.html_safe %></div>
<% end %>

<% if experiment.hardware_payload.present? %>
<p><strong>Hardware payload</strong></p>
<div id="hardware_payload"><%= experiment.hardware_payload.html_safe %></div>
<% end %>

<% if experiment.nanoracks.present? %>
<p><strong>Nanoracks</strong></p>
<div id="nanoracks"><%= experiment.nanoracks.html_safe %></div>
<% end %>

<p id="publications_count"><strong>Publications: <%= experiment.results_publications_count %></strong></p>

<% if experiment.link_url.present? %>
<p id="web"><strong>Web:</strong> <%= link_to experiment.link_text || experiment.link_url, experiment.link_url %></p>
<% end %>

<p>
  <table>
    <tr><th><%= pluralize experiment.investigators.size, "Principal Investigator" %></th></tr>
    <% experiment.investigators.each do |pi| %>
      <tr><td><%= link_to pi.name, pi %></td></tr>
    <% end %>
  </table>
</p>

<p>
  <table>
    <tr><th><%= pluralize experiment.developers.size, "Developer" %></th></tr>
    <% experiment.developers.each do |dev| %>
      <tr><td><%= link_to dev.name, dev %></td></tr>
    <% end %>
  </table>
</p>

app/views/experiments/_form.html.erb
<%= form_for(experiment) do |f| %>
  <% if experiment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
        <% experiment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Features</strong>
  </p>

  <p>
    <label>
    <%= f.check_box :completed_successfully %>
    Completed successfully
    </label>
  </p>

  <p>
    <label>
    <%= f.check_box :commercial %>
    Commercial
    </label>
  </p>

  <p>
    <label>
    <%= f.check_box :crew_involvement %>
    Crew involvement
    </label>
  </p>

  <p>
    <label>
    <%= f.check_box :required_sample_return %>
    Required sample return
    </label>
  </p>

  <p>
    <label>
    <%= f.check_box :hardware_required %>
    Hardware required
    </label>
  </p>

  <p>
    <label>
    <%= f.check_box :data_in_repositories %>
    Data in repositories
    </label>
  </p>

  <strong>Extra details</strong>

  <p>
    <label>
    Sample return:
    <%= f.number_field :sample_return_times, class: "small-number", min: 0 %>
    times
    </label>
    <%= f.label :crew_involvement_description, "Crew involvement description:", style: "color: #666" %>
    <%= f.text_field :crew_involvement_description %>
    <%= f.label :data_in_respositories_details, "Data respositories details:", style: "color: #666" %>
    <%= f.text_field :data_in_respositories_details %>
    <%= f.label :hardware_required_details, "Required hardware details:", style: "color: #666" %>
    <%= f.text_field :hardware_required_details %>
  </p>

  <strong>Keywords</strong>

  <p>
    <%= f.collection_check_boxes(:keyword_ids, Keyword.all, :id, :name)  do |b|
      b.label { b.check_box + b.text }
    end %>
  </p>


  <div>
    <% if experiment.revised %>
      <%= f.submit "Update" %>
    <% else %>
      <%= f.submit "Mark as revised" %>
    <% end %>
  </div>
<% end %>

app/views/experiments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Experiments <% if params[:by_initial].present? %>(<%= params[:by_initial].upcase %>)<% end %></h1>

<p>
<%= link_to "All", experiments_path %>
<% Experiment.initials.each do |letter| %>
  <% if params[:by_initial].present? && params[:by_initial].upcase == letter %>
    <strong><%= letter %></strong>
  <% else %>
    <%= link_to letter, experiments_path(by_initial: letter) %>
  <% end %>
<% end %>
</p>

<h3><%= pluralize @experiments.size, "experiment" %>: </h3>

<div id="experiments">
  <% @experiments.each do |experiment| %>
    <div id="<%= dom_id experiment %>">
      <p>
        <%= link_to experiment.name, experiment %>
        <%= revised_icon(experiment) %>
      </p>
    </div>
  <% end %>
</div>

app/views/experiments/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @experiment %>">
  <%= render @experiment %>
</div>