config/routes.rb
Rails.application.routes.draw do
  resources :experiments, only: [:index, :show, :update]

  resources :investigators, only: [:index, :show]
  resources :developers, only: [:index, :show]
  resources :expeditions, only: [:index, :show]
  resources :categories, only: [:index, :show]
  resources :subcategories, only: [:index, :show]
  resources :space_agencies, only: [:index, :show]
  resources :organizations, only: [:index, :show]
  resources :keywords

  root "experiments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :experiments

  default_scope { order(:name) }
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_and_belongs_to_many :experiments

  default_scope { order(:name) }
  scope :by_initial, ->(initial) { where("lower(name) LIKE ?", initial.downcase + "%") }

  def self.initials
    Developer.unscoped.all.select(:name).map {|e| e.name[0].upcase}.uniq.compact.sort
  end
end

app/models/expedition.rb
class Expedition < ApplicationRecord
  has_and_belongs_to_many :experiments

  default_scope { order(:name) }
end

app/models/experiment.rb
class Experiment < ApplicationRecord
  belongs_to :category
  belongs_to :subcategory
  belongs_to :space_agency
  belongs_to :organization
  has_and_belongs_to_many :developers
  has_and_belongs_to_many :expeditions
  has_and_belongs_to_many :investigators
  has_and_belongs_to_many :keywords

  validates :name, presence: true, uniqueness: true
  validates :external_id, presence: true, uniqueness: true

  default_scope { order(:name) }
  scope :unrevised, -> { where(revised: false) }
  scope :revised, -> { where(revised: true) }
  scope :complete, -> { includes(:category, :subcategory, :space_agency, :organization, :developers, :expeditions, :investigators, :keywords)}
  scope :by_initial, ->(initial) { where("lower(name) LIKE ?", initial.downcase + "%") }

  def self.initials
    Experiment.unscoped.all.select(:name).map {|e| e.name[0].upcase}.uniq.compact.sort
  end

  def revised!
    update_attribute(:revised, true)
  end

  def docking_dates
    dock_on = dock_date.present? ? dock_date.strftime("%d/%m/%Y") : "unavailable"
    undock_on = undock_date.present? ? undock_date.strftime("%d/%m/%Y") : "-"

    if dock_on == "unavailable" && undock_on == "-"
      return "No docking info available"
    else
      return "Docked from #{dock_on} to #{undock_on}"
    end
  end
end

app/models/investigator.rb
class Investigator < ApplicationRecord
  has_and_belongs_to_many :experiments

  default_scope { order(:name) }
  scope :by_initial, ->(initial) { where("lower(name) LIKE ?", initial.downcase + "%") }

  def self.initials
    Investigator.unscoped.all.select(:name).map {|e| e.name[0].upcase}.uniq.compact.sort
  end
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_and_belongs_to_many :experiments

  default_scope { order(:name) }

  validates_presence_of :variations, message: "At least one variation should be added"

  def variations_list
    self.variations.split(",").map(&:strip)
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :experiments

  default_scope { order(:name) }
end

app/models/principal_investigator.rb
class PrincipalInvestigator < ApplicationRecord
  has_and_belongs_to_many :experiments

  default_scope { order(:name) }
  scope :by_initial, ->(initial) { where("lower(name) LIKE ?", initial.downcase + "%") }

  def self.initials
    PrincipalInvestigator.unscoped.all.select(:name).map {|e| e.name[0].upcase}.uniq.compact.sort
  end
end

app/models/space_agency.rb
class SpaceAgency < ApplicationRecord
  has_many :experiments

  default_scope { order(:name) }
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :experiments

  default_scope { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def admin_required
    http_basic_authenticate_or_request_with name: ENV['ISS_USER'].to_s, password: ENV['ISS_PASS'].to_s
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    if params[:by_initial].present?
      @developers = Developer.by_initial(params[:by_initial])
    else
      @developers = Developer.all
    end
  end

  def show
    @developer = Developer.find(params[:id])
  end
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController
  def index
    @expeditions = Expedition.all
  end

  def show
    @expedition = Expedition.find(params[:id])
  end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :admin_required, except: [:index]

  def index
    if params[:by_initial].present?
      @experiments = Experiment.by_initial(params[:by_initial])
    else
      @experiments = Experiment.all
    end
  end

  def show
    @experiment = Experiment.complete.find(params[:id])
  end

  def update
    @experiment = Experiment.find(params[:id])
    if @experiment.update(experiment_params)
      @experiment.revised!
      redirect_to experiment_url(@experiment), notice: "Experiment was successfully updated!"
    else
      render :show, status: :unprocessable_entity
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def experiment_params
      params.require(:experiment).permit(:completed_successfully,
                                         :commercial,
                                         :crew_involvement,
                                         :required_sample_return,
                                         :hardware_required,
                                         :data_in_repositories,
                                         :sample_return_times,
                                         :crew_involvement_description,
                                         :data_in_respositories_details,
                                         :hardware_required_details,
                                         { keyword_ids: [] })
    end
end

app/controllers/investigators_controller.rb
class InvestigatorsController < ApplicationController
  def index
    if params[:by_initial].present?
      @investigators = Investigator.by_initial(params[:by_initial])
    else
      @investigators = Investigator.all
    end
  end

  def show
    @investigator = Investigator.find(params[:id])
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :admin_required, except: [:index, :show]

  def index
    @keywords = Keyword.all
  end

  def show
    @keyword = Keyword.includes(:experiments).find(params[:id])
  end

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)

    if @keyword.save
      redirect_to keywords_path, notice: 'Keyword added!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @keyword = Keyword.find(params[:id])
  end

  def update
    @keyword = Keyword.find(params[:id])
    if @keyword.update(keyword_params)
      redirect_to keywords_url, notice: 'Keyword updated!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @keyword.destroy
    redirect_to keywords_url, notice: 'Keyword destroyed!'
  end

  private

    def keyword_params
      params.require(:keyword).permit(:name, :variations)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
  end

  def show
    @organization = Organization.find(params[:id])
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def index
    @subcategories = Subcategory.all
  end

  def show
    @subcategory = Subcategory.find(params[:id])
    @experiments = @subcategory.experiments
    @experiments = @experiments.where(space_agency_id: params[:by_space_agency]) if params[:by_space_agency].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
  def revised_icon(exper, size=16)
    if exper.revised
      "<img src='/checked.png' width='#{size}px'>".html_safe
    end
  end
end

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <table>
    <tr><th>Category name</th></tr>
    <% @categories.each do |cat| %>
      <tr><td><%= link_to cat.name, cat %></td></tr>
    <% end %>
  </table>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to Categories list", categories_path %>

<h2><%= @category.name %></h2>

<p>
  <table>
    <tr><th><%= pluralize @category.experiments.size, "experiment" %> classified under <i><%= @category.name %></i></th></tr>
    <% @category.experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>

app/views/expeditions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Expeditions</h1>

<div id="expeditions">
  <table>
    <tr><th>Expedition</th></tr>
    <% @expeditions.each do |exp| %>
      <tr><td><%= link_to exp.name, exp %></td></tr>
    <% end %>
  </table>
</div>

app/views/expeditions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to Expeditions list", expeditions_path %>

<h2><%= @expedition.name %></h2>

<p>
  <table>
    <tr><th><%= pluralize @expedition.experiments.size, "experiment" %> during expedition <%= @expedition.name %></th></tr>
    <% @expedition.experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>

app/views/investigators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Principal Investigators</h1>

<p>
<%= link_to "All", investigators_path %>
<% Investigator.initials.each do |letter| %>
  <% if params[:by_initial].present? && params[:by_initial].upcase == letter %>
    <strong><%= letter %></strong>
  <% else %>
    <%= link_to letter, investigators_path(by_initial: letter) %>
  <% end %>
<% end %>
</p>

<h3><%= pluralize @investigators.size, "P.I." %>: </h3>

<div id="pi_list">
  <% @investigators.each do |pi| %>
    <div id="<%= dom_id pi %>">
      <p><%= link_to pi.name, pi %></p>
    </div>
  <% end %>
</div>

app/views/investigators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to P.I. list", investigators_path %>

<h2><%= @investigator.name.split(",")[0] %></h2>

<p><%= @investigator.name %></p>

<p>
  <table>
    <tr><th><%= pluralize @investigator.experiments.size, "Experiment" %></th></tr>
    <% @investigator.experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>

<div class="form-group">
  <div class="row">
    <div class="col">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="col">
      <%= f.label :variations, "Comma separated list" %>
      <%= f.text_field :variations, class: "form-control" %>
    </div>
  </div>
</div>


<div class="form-actions">
  <%= f.submit class: "btn paper-submit" %>
</div>
<% end %>

app/views/keywords/edit.html.erb
<div class="keywords">
  <div class="content">
    <h1>Editing Keyword</h1>
    <%= render 'form' %>

    <div class="links">
      <%= link_to 'Show', @keyword %> |
      <%= link_to 'Keywords list', keywords_path %>
    </div>
  </div>
</div>

app/views/keywords/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Keywords</h1>

<div id="keywords">
  <table>
    <tr><th>Keyword name</th><th>Variations</th></tr>
    <% @keywords.each do |key| %>
      <tr>
        <td class="keyword keyword-<%= key.id %>"><%= link_to key.name, key %></td>
        <td><%= key.variations %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/keywords/new.html.erb
<div class="new-keyword">
  <div class="content">
    <h1>New Keyword</h1>
    <%= render 'form' %>

    <div class="links">
      <%= link_to '&laquo; Back to keyword list'.html_safe, keywords_path %>
    </div>
  </div>
</div>

app/views/keywords/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to keywords list", keywords_path %>

<h2><%= @keyword.name %></h2>

<p>
  <table>
    <tr><th><%= pluralize @keyword.experiments.size, "experiment" %> tagged with <i><%= @keyword.name %></i></th></tr>
    <% @keyword.experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>

app/views/organizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organizations</h1>

<div id="organizations">
  <table>
    <tr><th>Organization</th></tr>
    <% @organizations.each do |organization| %>
      <tr><td><%= link_to organization.name, organization %></td></tr>
    <% end %>
  </table>
</div>

app/views/organizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to Organizations list", organizations_path %>

<h2><%= @organization.name %></h2>

<p>
  <table>
    <tr><th><%= pluralize @organization.experiments.size, "experiment" %> sponsored by <i><%= @organization.name %></i></th></tr>
    <% @organization.experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>

app/views/subcategories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subcategories</h1>

<div id="subcategories">
  <table>
    <tr><th>Subcategory name</th></tr>
    <% @subcategories.each do |subcat| %>
      <tr><td><%= link_to subcat.name, subcat %></td></tr>
    <% end %>
  </table>
</div>

app/views/subcategories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to "Back to Subcategories list", subcategories_path %>

<h2><%= @subcategory.name %></h2>

<%= select_tag :by_space_agency, options_from_collection_for_select(SpaceAgency.all, "id", "name", params[:by_space_agency].presence), include_blank: "All Space Agencies", onchange: "top.location.href='?by_space_agency=' + this.options[this.selectedIndex].value;" %>

<p>
  <table>
    <tr><th><%= pluralize @experiments.size, "experiment" %> classified under <i><%= @subcategory.name %></i></th></tr>
    <% @experiments.each do |ex| %>
      <tr><td><%= link_to ex.name, ex %> <%= revised_icon(ex) %></td></tr>
    <% end %>
  </table>
</p>